{
  "openapi": "3.0.0",
  "info": {
    "title": "Q-Vida API",
    "version": "0.1.0",
    "description": ""
  },
  "components": {
    "responses": {
      "Forbidden": {
        "description": "Access token is missing or invalid"
      },
      "Accepted": {
        "description": "The request was accepted"
      },
      "Created": {
        "description": "The resource has been created"
      },
      "NotFound": {
        "description": "The resource has been created"
      },
      "NotAcceptable": {
        "description": "The resource has been created"
      }
    },
    "securitySchemes": {
      "BearerAuth": {
        "type": "http",
        "scheme": "bearer"
      },
      "BasicAuth": {
        "type": "http",
        "scheme": "basic"
      },
      "ApiKeyAuth": {
        "type": "apiKey",
        "in": "header",
        "name": "X-API-Key"
      }
    },
    "schemas": {
      "Any": {
        "description": "Any JSON object not defined as schema"
      },
      "PaginationMeta": {
        "type": "object",
        "properties": {
          "total": {
            "type": "number",
            "example": 100,
            "nullable": false
          },
          "page": {
            "type": "number",
            "example": 2,
            "nullable": false
          },
          "perPage": {
            "type": "number",
            "example": 10,
            "nullable": false
          },
          "currentPage": {
            "type": "number",
            "example": 3,
            "nullable": false
          },
          "lastPage": {
            "type": "number",
            "example": 10,
            "nullable": false
          },
          "firstPage": {
            "type": "number",
            "example": 1,
            "nullable": false
          },
          "lastPageUrl": {
            "type": "string",
            "example": "/?page=10",
            "nullable": false
          },
          "firstPageUrl": {
            "type": "string",
            "example": "/?page=1",
            "nullable": false
          },
          "nextPageUrl": {
            "type": "string",
            "example": "/?page=6",
            "nullable": false
          },
          "previousPageUrl": {
            "type": "string",
            "example": "/?page=5",
            "nullable": false
          }
        }
      },
      "Bracelet": {
        "type": "object",
        "required": [],
        "properties": {
          "uid": {
            "type": "string",
            "example": "550e8400-e29b-41d4-a716-446655440000"
          },
          "state": {
            "type": "string",
            "example": "unassigned",
            "enum": [
              "unassigned",
              "assigned",
              "banned"
            ]
          },
          "assign_date": {
            "type": "string",
            "example": "2024-01-15",
            "format": "date-time"
          },
          "serial_number": {
            "type": "string",
            "example": "ABC123456"
          },
          "model": {
            "type": "string",
            "example": "desfire_EV3_4K"
          },
          "user": {
            "$ref": "#/components/schemas/User",
            "example": null
          }
        },
        "description": "Bracelet (Model)"
      },
      "MedPlumUser": {
        "type": "object",
        "required": [],
        "properties": {
          "user": {
            "$ref": "#/components/schemas/User",
            "example": null
          }
        },
        "description": "MedPlumUser (Model)"
      },
      "MedplumConfig": {
        "type": "object",
        "required": [],
        "properties": {
          "id": {
            "type": "number",
            "example": 678
          },
          "key": {
            "type": "string",
            "example": "Lorem Ipsum"
          },
          "value": {
            "type": "string",
            "example": "Lorem Ipsum"
          },
          "description": {
            "type": "string",
            "example": "Lorem ipsum dolor sit amet"
          },
          "created_at": {
            "$ref": "#/components/schemas/DateTime<boolean>",
            "example": null
          },
          "updated_at": {
            "$ref": "#/components/schemas/DateTime<boolean>",
            "example": null
          }
        },
        "description": "MedplumConfig (Model)"
      },
      "User": {
        "type": "object",
        "required": [],
        "properties": {
          "uid": {
            "type": "string",
            "example": "550e8400-e29b-41d4-a716-446655440000"
          },
          "first_name": {
            "type": "string",
            "example": "Pepito"
          },
          "surnames": {
            "type": "string",
            "example": "Perez"
          },
          "email": {
            "type": "string",
            "example": "johndoe@example.com",
            "format": "email"
          },
          "role": {
            "type": "string",
            "example": "Patient"
          }
        },
        "description": "User (Model)"
      },
      "assignBraceletValidator": {
        "type": "object",
        "properties": {
          "user_uuid": {
            "type": "string",
            "example": "Lorem Ipsum",
            "required": true
          },
          "bracelet_uuid": {
            "type": "string",
            "example": "Lorem Ipsum",
            "required": true
          }
        },
        "example": {
          "user_uuid": "Lorem Ipsum",
          "bracelet_uuid": "Lorem Ipsum"
        },
        "description": "assignBraceletValidator (Validator)"
      },
      "banBraceletValidator": {
        "type": "object",
        "properties": {
          "bracelet_uuid": {
            "type": "string",
            "example": "Lorem Ipsum",
            "required": true
          }
        },
        "example": {
          "bracelet_uuid": "Lorem Ipsum"
        },
        "description": "banBraceletValidator (Validator)"
      },
      "createBraceletValidator": {
        "type": "object",
        "properties": {
          "model": {
            "type": "string",
            "example": "Lorem Ipsum",
            "required": true
          },
          "serial_number": {
            "type": "string",
            "example": "Lorem Ipsum",
            "required": true,
            "minLength": 8
          }
        },
        "example": {
          "model": "Lorem Ipsum",
          "serial_number": "Lorem Ipsum"
        },
        "description": "createBraceletValidator (Validator)"
      },
      "idParamValidator": {
        "type": "object",
        "properties": {
          "id": {
            "type": "number",
            "example": 824,
            "required": true
          }
        },
        "example": {
          "id": 824
        },
        "description": "idParamValidator (Validator)"
      },
      "uidValidator": {
        "type": "object",
        "properties": {
          "uid": {
            "type": "string",
            "example": "Lorem Ipsum",
            "required": true
          }
        },
        "example": {
          "uid": "Lorem Ipsum"
        },
        "description": "uidValidator (Validator)"
      },
      "storeCondition": {
        "type": "object",
        "properties": {
          "allergies": {
            "type": "array",
            "items": {
              "type": "number",
              "example": 139
            },
            "required": true,
            "properties": {
              "items": {
                "type": "string",
                "example": "Lorem Ipsum"
              }
            }
          },
          "medications": {
            "type": "array",
            "items": {
              "type": "number",
              "example": 393
            },
            "required": true,
            "properties": {
              "items": {
                "type": "string",
                "example": "Lorem Ipsum"
              }
            }
          },
          "pathologies": {
            "type": "array",
            "items": {
              "type": "number",
              "example": 147
            },
            "required": true,
            "properties": {
              "items": {
                "type": "string",
                "example": "Lorem Ipsum"
              }
            }
          },
          "inplantDevices": {
            "type": "array",
            "items": {
              "type": "number",
              "example": 569
            },
            "required": true,
            "properties": {
              "items": {
                "type": "string",
                "example": "Lorem Ipsum"
              }
            }
          },
          "neurologicalStatus": {
            "type": "array",
            "items": {
              "type": "number",
              "example": 812
            },
            "required": true,
            "properties": {
              "items": {
                "type": "string",
                "example": "Lorem Ipsum"
              }
            }
          },
          "firstName": {
            "type": "string",
            "example": "Lorem Ipsum",
            "required": true
          },
          "surnames": {
            "type": "string",
            "example": "Lorem Ipsum",
            "required": true
          },
          "language": {
            "type": "number",
            "example": 351,
            "choices": [
              "ES",
              "EN"
            ],
            "required": true
          },
          "biologicalSex": {
            "type": "number",
            "example": 329,
            "choices": [
              "M",
              "F"
            ],
            "required": true
          },
          "bloodType": {
            "type": "number",
            "example": 755,
            "choices": [
              "O+",
              "O-",
              "A+",
              "A-",
              "B+",
              "B-",
              "AB+",
              "AB-"
            ],
            "required": true
          }
        },
        "example": {
          "allergies": [
            "Lorem Ipsum"
          ],
          "medications": [
            "Lorem Ipsum"
          ],
          "pathologies": [
            "Lorem Ipsum"
          ],
          "inplantDevices": [
            "Lorem Ipsum"
          ],
          "neurologicalStatus": [
            "Lorem Ipsum"
          ],
          "firstName": "Lorem Ipsum",
          "surnames": "Lorem Ipsum",
          "language": 351,
          "biologicalSex": 329,
          "bloodType": 755
        },
        "description": "storeCondition (Validator)"
      },
      "adminSignupValidator": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "example": "Lorem Ipsum",
            "required": true,
            "minLength": 3,
            "maxLength": 50
          },
          "email": {
            "type": "string",
            "example": "Lorem Ipsum",
            "required": true,
            "maxLength": 254
          },
          "password": {
            "type": "string",
            "example": "Lorem Ipsum",
            "required": true,
            "minLength": 8,
            "maxLength": 32
          },
          "passwordConfirmation": {
            "type": "string",
            "example": "Lorem Ipsum",
            "required": true,
            "minLength": 8,
            "maxLength": 32
          }
        },
        "example": {
          "name": "Lorem Ipsum",
          "email": "Lorem Ipsum",
          "password": "Lorem Ipsum",
          "passwordConfirmation": "Lorem Ipsum"
        },
        "description": "adminSignupValidator (Validator)"
      },
      "loginValidator": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "example": "Lorem Ipsum",
            "required": true,
            "maxLength": 254
          },
          "password": {
            "type": "string",
            "example": "Lorem Ipsum",
            "required": true
          }
        },
        "example": {
          "email": "Lorem Ipsum",
          "password": "Lorem Ipsum"
        },
        "description": "loginValidator (Validator)"
      },
      "onceAdminSignupValidator": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "example": "Lorem Ipsum",
            "required": true,
            "maxLength": 254
          },
          "password": {
            "type": "string",
            "example": "Lorem Ipsum",
            "required": true,
            "minLength": 8,
            "maxLength": 32
          },
          "passwordConfirmation": {
            "type": "string",
            "example": "Lorem Ipsum",
            "required": true,
            "minLength": 8,
            "maxLength": 32
          }
        },
        "example": {
          "email": "Lorem Ipsum",
          "password": "Lorem Ipsum",
          "passwordConfirmation": "Lorem Ipsum"
        },
        "description": "onceAdminSignupValidator (Validator)"
      },
      "signupValidator": {
        "type": "object",
        "properties": {
          "firstName": {
            "type": "string",
            "example": "Lorem Ipsum",
            "required": true
          },
          "surnames": {
            "type": "string",
            "example": "Lorem Ipsum",
            "required": true
          },
          "email": {
            "type": "string",
            "example": "Lorem Ipsum",
            "required": true,
            "maxLength": 254
          },
          "role": {
            "type": "number",
            "example": 91,
            "choices": [
              "Patient",
              "Practitioner"
            ],
            "required": true
          },
          "password": {
            "type": "string",
            "example": "Lorem Ipsum",
            "required": true,
            "minLength": 8,
            "maxLength": 32
          },
          "passwordConfirmation": {
            "type": "string",
            "example": "Lorem Ipsum",
            "required": true,
            "minLength": 8,
            "maxLength": 32
          }
        },
        "example": {
          "firstName": "Lorem Ipsum",
          "surnames": "Lorem Ipsum",
          "email": "Lorem Ipsum",
          "role": 91,
          "password": "Lorem Ipsum",
          "passwordConfirmation": "Lorem Ipsum"
        },
        "description": "signupValidator (Validator)"
      }
    }
  },
  "paths": {
    "/": {
      "get": {
        "summary": "route",
        "description": "\n\n __ - ****",
        "parameters": [],
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {}
            }
          }
        },
        "security": []
      }
    },
    "/api/v1/auth/register": {
      "post": {
        "summary": "Register an account (store)",
        "description": "\n\n _app/controllers/new_account_controller.ts_ - **store**",
        "parameters": [],
        "tags": [
          "AUTH"
        ],
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {}
            }
          }
        },
        "security": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/signupValidator"
              },
              "example": {
                "firstName": "Lorem Ipsum",
                "surnames": "Lorem Ipsum",
                "email": "Lorem Ipsum",
                "role": 91,
                "password": "Lorem Ipsum",
                "passwordConfirmation": "Lorem Ipsum"
              }
            }
          }
        }
      }
    },
    "/api/v1/auth/login": {
      "post": {
        "summary": "Login an account (store)",
        "description": "\n\n _app/controllers/access_token_controller.ts_ - **store**",
        "parameters": [],
        "tags": [
          "AUTH"
        ],
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {}
            }
          }
        },
        "security": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/loginValidator"
              },
              "example": {
                "email": "Lorem Ipsum",
                "password": "Lorem Ipsum"
              }
            }
          }
        }
      }
    },
    "/api/v1/auth/logout": {
      "post": {
        "summary": "Logout (destroy)",
        "description": "\n\n _app/controllers/access_token_controller.ts_ - **destroy**",
        "parameters": [],
        "tags": [
          "AUTH"
        ],
        "responses": {
          "401": {
            "description": "Returns **401** (Unauthorized)"
          },
          "403": {
            "description": "Returns **403** (Forbidden)"
          }
        },
        "security": [
          {
            "BearerAuth": [
              "access"
            ]
          }
        ]
      }
    },
    "/api/v1/admin/register-once": {
      "post": {
        "summary": "Register once an admin. (storeAdminOnce)",
        "description": "Register an admin account if there are no admins\n\n _app/controllers/new_account_controller.ts_ - **storeAdminOnce**",
        "parameters": [],
        "tags": [
          "ADMIN"
        ],
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {}
            }
          }
        },
        "security": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/onceAdminSignupValidator"
              },
              "example": {
                "email": "Lorem Ipsum",
                "password": "Lorem Ipsum",
                "passwordConfirmation": "Lorem Ipsum"
              }
            }
          }
        }
      }
    },
    "/api/v1/admin/register": {
      "post": {
        "summary": "Register an admin. (storeAdmin)",
        "description": "Register an admin account if you are an admin\n\n _app/controllers/new_account_controller.ts_ - **storeAdmin**",
        "parameters": [],
        "tags": [
          "ADMIN"
        ],
        "responses": {
          "401": {
            "description": "Returns **401** (Unauthorized)"
          },
          "403": {
            "description": "Returns **403** (Forbidden)"
          }
        },
        "security": [
          {
            "BearerAuth": [
              "access"
            ]
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/adminSignupValidator"
              },
              "example": {
                "name": "Lorem Ipsum",
                "email": "Lorem Ipsum",
                "password": "Lorem Ipsum",
                "passwordConfirmation": "Lorem Ipsum"
              }
            }
          }
        }
      }
    },
    "/api/v1/account/profile": {
      "get": {
        "summary": "Get your account data (show)",
        "description": "\n\n _app/controllers/profile_controller.ts_ - **show**",
        "parameters": [],
        "tags": [
          "ACCOUNT"
        ],
        "responses": {
          "401": {
            "description": "Returns **401** (Unauthorized)"
          },
          "403": {
            "description": "Returns **403** (Forbidden)"
          }
        },
        "security": [
          {
            "BearerAuth": [
              "access"
            ]
          }
        ]
      }
    },
    "/api/v1/bracelet": {
      "get": {
        "summary": "List all bracelets (index)",
        "description": "Returns **200** (OK) as **application/json**\n\n _app/controllers/bracelets_controller.ts_ - **index**",
        "parameters": [],
        "tags": [
          "BRACELET"
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Bracelet"
                  }
                },
                "example": [
                  {
                    "uid": "550e8400-e29b-41d4-a716-446655440000",
                    "state": "unassigned",
                    "assign_date": "2024-01-15",
                    "serial_number": "ABC123456",
                    "model": "desfire_EV3_4K",
                    "user": {
                      "uid": "550e8400-e29b-41d4-a716-446655440000",
                      "first_name": "Pepito",
                      "surnames": "Perez",
                      "email": "johndoe@example.com",
                      "role": "Patient"
                    }
                  }
                ]
              }
            },
            "description": "Returns **200** (OK) as **application/json**"
          },
          "401": {
            "description": "Returns **401** (Unauthorized)"
          },
          "403": {
            "description": "Returns **403** (Forbidden)"
          }
        },
        "security": [
          {
            "BearerAuth": [
              "access"
            ]
          }
        ]
      }
    },
    "/api/v1/bracelet/models": {
      "get": {
        "summary": "List all supported models (models)",
        "description": "\n\n _app/controllers/bracelets_controller.ts_ - **models**",
        "parameters": [],
        "tags": [
          "BRACELET"
        ],
        "responses": {
          "401": {
            "description": "Returns **401** (Unauthorized)"
          },
          "403": {
            "description": "Returns **403** (Forbidden)"
          }
        },
        "security": [
          {
            "BearerAuth": [
              "access"
            ]
          }
        ]
      }
    },
    "/api/v1/bracelet/user/{userUid}": {
      "get": {
        "summary": "Show bracelet by user uid (showByUser)",
        "description": "Returns **200** (OK) as **application/json**\n\n _app/controllers/bracelets_controller.ts_ - **showByUser**",
        "parameters": [
          {
            "in": "path",
            "name": "userUid",
            "schema": {
              "type": "string"
            },
            "required": true
          }
        ],
        "tags": [
          "BRACELET"
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Bracelet"
                },
                "example": {
                  "uid": "550e8400-e29b-41d4-a716-446655440000",
                  "state": "unassigned",
                  "assign_date": "2024-01-15",
                  "serial_number": "ABC123456",
                  "model": "desfire_EV3_4K"
                }
              }
            },
            "description": "Returns **200** (OK) as **application/json**"
          },
          "401": {
            "description": "Returns **401** (Unauthorized)"
          },
          "403": {
            "description": "Returns **403** (Forbidden)"
          }
        },
        "security": [
          {
            "BearerAuth": [
              "access"
            ]
          }
        ]
      }
    },
    "/api/v1/bracelet/{uid}": {
      "get": {
        "summary": "Show bracelet by uid (show)",
        "description": "Returns **200** (OK) as **application/json**\n\n _app/controllers/bracelets_controller.ts_ - **show**",
        "parameters": [
          {
            "in": "path",
            "name": "uid",
            "schema": {
              "type": "string"
            },
            "required": true
          }
        ],
        "tags": [
          "BRACELET"
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Bracelet"
                },
                "example": {
                  "uid": "550e8400-e29b-41d4-a716-446655440000",
                  "state": "unassigned",
                  "assign_date": "2024-01-15",
                  "serial_number": "ABC123456",
                  "model": "desfire_EV3_4K"
                }
              }
            },
            "description": "Returns **200** (OK) as **application/json**"
          },
          "401": {
            "description": "Returns **401** (Unauthorized)"
          },
          "403": {
            "description": "Returns **403** (Forbidden)"
          }
        },
        "security": [
          {
            "BearerAuth": [
              "access"
            ]
          }
        ]
      }
    },
    "/api/v1/bracelet/create": {
      "post": {
        "summary": "Create a bracelet (store)",
        "description": "\n\n _app/controllers/bracelets_controller.ts_ - **store**",
        "parameters": [],
        "tags": [
          "BRACELET"
        ],
        "responses": {
          "401": {
            "description": "Returns **401** (Unauthorized)"
          },
          "403": {
            "description": "Returns **403** (Forbidden)"
          }
        },
        "security": [
          {
            "BearerAuth": [
              "access"
            ]
          }
        ]
      }
    },
    "/api/v1/bracelet/assign": {
      "post": {
        "summary": "Assign a bracelet to an user (assign)",
        "description": "\n\n _app/controllers/bracelets_controller.ts_ - **assign**",
        "parameters": [],
        "tags": [
          "BRACELET"
        ],
        "responses": {
          "401": {
            "description": "Returns **401** (Unauthorized)"
          },
          "403": {
            "description": "Returns **403** (Forbidden)"
          }
        },
        "security": [
          {
            "BearerAuth": [
              "access"
            ]
          }
        ]
      }
    },
    "/api/v1/bracelet/ban/{braceletUuid}": {
      "patch": {
        "summary": "Bans a bracelet (banByUid)",
        "description": "\n\n _app/controllers/bracelets_controller.ts_ - **banByUid**",
        "parameters": [
          {
            "in": "path",
            "name": "braceletUuid",
            "schema": {
              "type": "string"
            },
            "required": true
          }
        ],
        "tags": [
          "BRACELET"
        ],
        "responses": {
          "401": {
            "description": "Returns **401** (Unauthorized)"
          },
          "403": {
            "description": "Returns **403** (Forbidden)"
          }
        },
        "security": [
          {
            "BearerAuth": [
              "access"
            ]
          }
        ]
      }
    },
    "/api/v1/data/allergies": {
      "get": {
        "summary": "Available allergies (allergies)",
        "description": "List all allergies in SNOMEDE_CT estandard\n\n _app/controllers/data_controller.ts_ - **allergies**",
        "parameters": [],
        "tags": [
          "DATA"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {}
            }
          }
        },
        "security": []
      }
    },
    "/api/v1/data/medications": {
      "get": {
        "summary": "Available medications (medications)",
        "description": "List all medications in SNOMEDE_CT estandard\n\n _app/controllers/data_controller.ts_ - **medications**",
        "parameters": [],
        "tags": [
          "DATA"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {}
            }
          }
        },
        "security": []
      }
    },
    "/api/v1/data/pathologies": {
      "get": {
        "summary": "Available pathologies (pathologies)",
        "description": "List all pathologies in SNOMEDE_CT estandard\n\n _app/controllers/data_controller.ts_ - **pathologies**",
        "parameters": [],
        "tags": [
          "DATA"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {}
            }
          }
        },
        "security": []
      }
    },
    "/api/v1/data/implant-devices": {
      "get": {
        "summary": "Available inplant devices (inplantDevices)",
        "description": "List all inplant devices in SNOMEDE_CT estandard\n\n _app/controllers/data_controller.ts_ - **inplantDevices**",
        "parameters": [],
        "tags": [
          "DATA"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {}
            }
          }
        },
        "security": []
      }
    },
    "/api/v1/data/neurological-status": {
      "get": {
        "summary": "Available neurological status devices (neurologicalStatus)",
        "description": "List all neurological status in SNOMEDE_CT estandard\n\n _app/controllers/data_controller.ts_ - **neurologicalStatus**",
        "parameters": [],
        "tags": [
          "DATA"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {}
            }
          }
        },
        "security": []
      }
    },
    "/api/v1/me": {
      "get": {
        "summary": "Get self medical data (show)",
        "description": "\n\n _app/controllers/us_controller.ts_ - **show**",
        "parameters": [],
        "tags": [
          "ME"
        ],
        "responses": {
          "401": {
            "description": "Returns **401** (Unauthorized)"
          },
          "403": {
            "description": "Returns **403** (Forbidden)"
          }
        },
        "security": [
          {
            "BearerAuth": [
              "access"
            ]
          }
        ]
      },
      "put": {
        "summary": "Update self medical data (update)",
        "description": "Replace all data (be careful bro)\n\n _app/controllers/us_controller.ts_ - **update**",
        "parameters": [],
        "tags": [
          "ME"
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {}
              }
            },
            "description": "Returns **200** (OK) as **application/json**"
          },
          "401": {
            "description": "Returns **401** (Unauthorized)"
          },
          "403": {
            "description": "Returns **403** (Forbidden)"
          }
        },
        "security": [
          {
            "BearerAuth": [
              "access"
            ]
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/storeCondition"
              },
              "example": {
                "allergies": [
                  "Lorem Ipsum"
                ],
                "medications": [
                  "Lorem Ipsum"
                ],
                "pathologies": [
                  "Lorem Ipsum"
                ],
                "inplantDevices": [
                  "Lorem Ipsum"
                ],
                "neurologicalStatus": [
                  "Lorem Ipsum"
                ],
                "firstName": "Lorem Ipsum",
                "surnames": "Lorem Ipsum",
                "language": 351,
                "biologicalSex": 329,
                "bloodType": 755
              }
            }
          }
        }
      },
      "post": {
        "summary": "Store patient medical conditions (store)",
        "description": "Creates allergies, pathologies and other conditions for authenticated user\n\n _app/controllers/us_controller.ts_ - **store**",
        "parameters": [],
        "tags": [
          "ME"
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {}
              }
            },
            "description": "Returns **200** (OK) as **application/json**"
          },
          "401": {
            "description": "Returns **401** (Unauthorized)"
          },
          "403": {
            "description": "Returns **403** (Forbidden)"
          }
        },
        "security": [
          {
            "BearerAuth": [
              "access"
            ]
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/storeCondition"
              },
              "example": {
                "allergies": [
                  "Lorem Ipsum"
                ],
                "medications": [
                  "Lorem Ipsum"
                ],
                "pathologies": [
                  "Lorem Ipsum"
                ],
                "inplantDevices": [
                  "Lorem Ipsum"
                ],
                "neurologicalStatus": [
                  "Lorem Ipsum"
                ],
                "firstName": "Lorem Ipsum",
                "surnames": "Lorem Ipsum",
                "language": 351,
                "biologicalSex": 329,
                "bloodType": 755
              }
            }
          }
        }
      }
    },
    "/api/v1/me/uid/{userUid}": {
      "get": {
        "summary": "Get user medical data by UID (showByUid)",
        "description": "\n\n _app/controllers/us_controller.ts_ - **showByUid**",
        "parameters": [
          {
            "in": "path",
            "name": "userUid",
            "schema": {
              "type": "string"
            },
            "required": true
          }
        ],
        "tags": [
          "ME"
        ],
        "responses": {
          "401": {
            "description": "Returns **401** (Unauthorized)"
          },
          "403": {
            "description": "Returns **403** (Forbidden)"
          }
        },
        "security": [
          {
            "BearerAuth": [
              "access"
            ]
          }
        ]
      },
      "post": {
        "summary": "Store patient medical conditions by Uid (storeByUid)",
        "description": "Creates allergies, pathologies and other conditions for authenticated user\n\n _app/controllers/us_controller.ts_ - **storeByUid**",
        "parameters": [
          {
            "in": "path",
            "name": "userUid",
            "schema": {
              "type": "string"
            },
            "required": true
          }
        ],
        "tags": [
          "ME"
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {}
              }
            },
            "description": "Returns **200** (OK) as **application/json**"
          },
          "401": {
            "description": "Returns **401** (Unauthorized)"
          },
          "403": {
            "description": "Returns **403** (Forbidden)"
          }
        },
        "security": [
          {
            "BearerAuth": [
              "access"
            ]
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/storeCondition"
              },
              "example": {
                "allergies": [
                  "Lorem Ipsum"
                ],
                "medications": [
                  "Lorem Ipsum"
                ],
                "pathologies": [
                  "Lorem Ipsum"
                ],
                "inplantDevices": [
                  "Lorem Ipsum"
                ],
                "neurologicalStatus": [
                  "Lorem Ipsum"
                ],
                "firstName": "Lorem Ipsum",
                "surnames": "Lorem Ipsum",
                "language": 351,
                "biologicalSex": 329,
                "bloodType": 755
              }
            }
          }
        }
      }
    },
    "/api/v1/me/bracelet/{braceletUid}": {
      "get": {
        "summary": "Get user medical data by UID (showByBraceletUid)",
        "description": "\n\n _app/controllers/us_controller.ts_ - **showByBraceletUid**",
        "parameters": [
          {
            "in": "path",
            "name": "braceletUid",
            "schema": {
              "type": "string"
            },
            "required": true
          }
        ],
        "tags": [
          "ME"
        ],
        "responses": {
          "401": {
            "description": "Returns **401** (Unauthorized)"
          },
          "403": {
            "description": "Returns **403** (Forbidden)"
          }
        },
        "security": [
          {
            "BearerAuth": [
              "access"
            ]
          }
        ]
      }
    },
    "/api/v1/proxy/profiles/{profileType}/{userUid}": {
      "get": {
        "summary": "Show all medplum users (show)",
        "description": "Returns **200** (OK) as **text/plain**\n\n _app/controllers/medplum_controller.ts_ - **show**",
        "parameters": [
          {
            "in": "path",
            "name": "profileType",
            "schema": {
              "type": "string"
            },
            "required": true
          },
          {
            "in": "path",
            "name": "userUid",
            "schema": {
              "type": "string"
            },
            "required": true
          }
        ],
        "tags": [
          "PROXY"
        ],
        "responses": {
          "200": {
            "content": {
              "text/plain": {
                "example": "{ \"membershipId\": \"123\", \"profileType\": \"Practitioner\", profileId: 1 }"
              }
            },
            "description": "Returns **200** (OK) as **text/plain**"
          },
          "401": {
            "description": "Returns **401** (Unauthorized)"
          },
          "403": {
            "description": "Returns **403** (Forbidden)"
          }
        },
        "security": [
          {
            "BearerAuth": [
              "access"
            ]
          }
        ]
      },
      "put": {
        "summary": "Update profile data (update)",
        "description": "\n\n _app/controllers/medplum_controller.ts_ - **update**",
        "parameters": [
          {
            "in": "path",
            "name": "profileType",
            "schema": {
              "type": "string"
            },
            "required": true
          },
          {
            "in": "path",
            "name": "userUid",
            "schema": {
              "type": "string"
            },
            "required": true
          }
        ],
        "tags": [
          "PROXY"
        ],
        "responses": {
          "200": {
            "content": {
              "text/plain": {
                "example": "{ data: {}, \"membershipId\": \"123\", \"profileType\": \"Practitioner\", profileId: 1 }"
              }
            },
            "description": "Returns **200** (OK) as **text/plain**"
          },
          "401": {
            "description": "Returns **401** (Unauthorized)"
          },
          "403": {
            "description": "Returns **403** (Forbidden)"
          }
        },
        "security": [
          {
            "BearerAuth": [
              "access"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Deletes an medplum user (destroy)",
        "description": "\n\n _app/controllers/medplum_controller.ts_ - **destroy**",
        "parameters": [
          {
            "in": "path",
            "name": "profileType",
            "schema": {
              "type": "string"
            },
            "required": true
          },
          {
            "in": "path",
            "name": "userUid",
            "schema": {
              "type": "string"
            },
            "required": true
          }
        ],
        "tags": [
          "PROXY"
        ],
        "responses": {
          "401": {
            "description": "Returns **401** (Unauthorized)"
          },
          "403": {
            "description": "Returns **403** (Forbidden)"
          }
        },
        "security": [
          {
            "BearerAuth": [
              "access"
            ]
          }
        ]
      }
    },
    "/api/v1/proxy/profiles/{profileType}": {
      "get": {
        "summary": "List all medplum profiles (index)",
        "description": "Returns **200** (OK) as **application/json**\n\n _app/controllers/medplum_controller.ts_ - **index**",
        "parameters": [
          {
            "in": "path",
            "name": "profileType",
            "schema": {
              "type": "string"
            },
            "required": true
          }
        ],
        "tags": [
          "PROXY"
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object"
                  }
                },
                "example": [
                  {
                    "membershipId": "123",
                    "profileType": "Practitioner"
                  }
                ]
              }
            },
            "description": "Returns **200** (OK) as **application/json**"
          },
          "401": {
            "description": "Returns **401** (Unauthorized)"
          },
          "403": {
            "description": "Returns **403** (Forbidden)"
          }
        },
        "security": [
          {
            "BearerAuth": [
              "access"
            ]
          }
        ]
      }
    },
    "/api/v1/proxy/clinical/{profileType}/{userUid}/{resourceType}": {
      "get": {
        "summary": "Gets info (getInfo)",
        "description": "\n\n _app/controllers/medplum_controller.ts_ - **getInfo**",
        "parameters": [
          {
            "in": "path",
            "name": "profileType",
            "schema": {
              "type": "string"
            },
            "required": true
          },
          {
            "in": "path",
            "name": "userUid",
            "schema": {
              "type": "string"
            },
            "required": true
          },
          {
            "in": "path",
            "name": "resourceType",
            "schema": {
              "type": "string"
            },
            "required": true
          }
        ],
        "tags": [
          "PROXY"
        ],
        "responses": {
          "401": {
            "description": "Returns **401** (Unauthorized)"
          },
          "403": {
            "description": "Returns **403** (Forbidden)"
          }
        },
        "security": [
          {
            "BearerAuth": [
              "access"
            ]
          }
        ]
      }
    }
  },
  "tags": [
    {
      "name": "AUTH",
      "description": "Everything related to AUTH"
    },
    {
      "name": "ADMIN",
      "description": "Everything related to ADMIN"
    },
    {
      "name": "ACCOUNT",
      "description": "Everything related to ACCOUNT"
    },
    {
      "name": "BRACELET",
      "description": "Everything related to BRACELET"
    },
    {
      "name": "DATA",
      "description": "Everything related to DATA"
    },
    {
      "name": "ME",
      "description": "Everything related to ME"
    },
    {
      "name": "PROXY",
      "description": "Everything related to PROXY"
    }
  ]
}